name: seqparse Test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      # Setup Python (faster than using Python container)
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10.0"
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      - name: Install seqparse
        run: |
          pip install .
      - name: Run pytest
        run: |
          pytest -v